#!/usr/bin/env bash
#
# Plugin: Journald Configuration
# Limits systemd journal size to prevent SD card wear
#

PLUGIN_NAME="journald"
PLUGIN_VERSION="1.0"
PLUGIN_DEPENDS=()
PLUGIN_PHASES=("post-install")

# Source logging
if ! command -v log_info &>/dev/null; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../.. && pwd)"
    source "${SCRIPT_DIR}/lib/log.sh"
fi

plugin_run_post_install() {
    log_set_phase "journald-post-install"
    log_info "Journald: Configuring journal size limits"
    
    local journald_conf="${MOUNT_POINT}/etc/systemd/journald.conf"
    
    if [[ ! -f "$journald_conf" ]]; then
        log_warn "Journald: journald.conf not found, creating"
        mkdir -p "$(dirname "$journald_conf")"
        cat > "$journald_conf" << 'EOF'
# journald.conf - systemd journal configuration
# Auto-generated by Manjaro ARM installer

[Journal]
EOF
    fi
    
    # Configure journal limits to reduce SD card wear
    log_info "Journald: Setting size limits (SystemMaxUse=100M, MaxRetentionSec=1week)"
    
    # Remove existing settings if present
    sed -i '/^SystemMaxUse=/d' "$journald_conf"
    sed -i '/^SystemKeepFree=/d' "$journald_conf"
    sed -i '/^RuntimeMaxUse=/d' "$journald_conf"
    sed -i '/^MaxRetentionSec=/d' "$journald_conf"
    sed -i '/^MaxFileSec=/d' "$journald_conf"
    
    # Add optimized settings
    if ! grep -q "^\[Journal\]" "$journald_conf"; then
        echo "[Journal]" >> "$journald_conf"
    fi
    
    cat >> "$journald_conf" << 'EOF'

# Limit journal size to reduce SD card wear (configured by installer)
SystemMaxUse=100M
SystemKeepFree=500M
RuntimeMaxUse=50M
MaxRetentionSec=1week
MaxFileSec=1day
EOF
    
    log_info "Journald: Configuration complete"
    log_info "Journald: Journal limited to 100MB, 1 week retention"
    
    return 0
}
