#!/usr/bin/env bash
#
# Plugin: Xorg Configuration
# Configures X11 display server for Raspberry Pi 5
#

PLUGIN_NAME="xorg"
PLUGIN_VERSION="1.0"
PLUGIN_DEPENDS=()
PLUGIN_PHASES=("config")

# Source logging
if ! command -v log_info &>/dev/null; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../.. && pwd)"
    source "${SCRIPT_DIR}/lib/log.sh"
fi

plugin_run_config() {
    log_set_phase "xorg-config"
    
    # Skip Xorg configuration for minimal edition
    if [[ "${EDITION:-}" == "minimal" ]]; then
        log_info "Xorg: Skipping configuration (minimal edition)"
        return 0
    fi
    
    log_info "Xorg: Configuring X11 display server"
    
    local xorg_conf_dir="${MOUNT_POINT}/etc/X11/xorg.conf.d"
    mkdir -p "$xorg_conf_dir"
    
    # Create optimized Xorg configuration for Raspberry Pi 5
    local pi5_xorg_conf="${xorg_conf_dir}/20-pi5-vc4.conf"
    
    log_info "Xorg: Creating Pi 5 optimized configuration"
    
    cat > "$pi5_xorg_conf" << 'EOF'
# Raspberry Pi 5 Xorg Configuration
# Auto-generated by Manjaro ARM installer

Section "Device"
    Identifier  "Raspberry Pi 5 VC4"
    Driver      "modesetting"
    Option      "AccelMethod" "glamor"
    Option      "DRI" "3"
EndSection

Section "ServerFlags"
    Option "AutoAddGPU" "off"
EndSection

Section "OutputClass"
    Identifier "vc4"
    MatchDriver "vc4"
    Driver "modesetting"
    Option "PrimaryGPU" "true"
EndSection
EOF
    
    log_info "Xorg: Created VC4 modesetting configuration"
    
    # Create input configuration for better touchscreen/mouse support
    local input_conf="${xorg_conf_dir}/40-libinput.conf"
    
    cat > "$input_conf" << 'EOF'
# Input device configuration
# Auto-generated by Manjaro ARM installer

Section "InputClass"
    Identifier "libinput pointer catchall"
    MatchIsPointer "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
EndSection

Section "InputClass"
    Identifier "libinput keyboard catchall"
    MatchIsKeyboard "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
EndSection

Section "InputClass"
    Identifier "libinput touchpad catchall"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
EndSection

Section "InputClass"
    Identifier "libinput touchscreen catchall"
    MatchIsTouchscreen "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
EndSection
EOF
    
    log_info "Xorg: Created input device configuration"
    
    # Set proper permissions
    chmod 644 "$pi5_xorg_conf" "$input_conf"
    
    log_info "Xorg: Configuration complete"
    log_info "Xorg: Using VC4 modesetting with DRI3 and GLAMOR acceleration"
    
    return 0
}
